# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mybreaks_rcpp <- function(x, nbr) {
    .Call(`_CppFunctions_mybreaks_rcpp`, x, nbr)
}

hist_rcpp <- function(x, breaks) {
    .Call(`_CppFunctions_hist_rcpp`, x, breaks)
}

riskhistRcpp <- function(obs01, m) {
    .Call(`_CppFunctions_riskhistRcpp`, obs01, m)
}

broptRcpp <- function(x) {
    .Call(`_CppFunctions_broptRcpp`, x)
}

riskhist_and_fp_Rcpp <- function(obs01, m) {
    .Call(`_CppFunctions_riskhist_and_fp_Rcpp`, obs01, m)
}

bropt_and_broptfp_Rcpp <- function(x) {
    .Call(`_CppFunctions_bropt_and_broptfp_Rcpp`, x)
}

